Document: asynk
Title: Debian asynk Manual
Author: <insert document author here>
Abstract: This manual describes what asynk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/asynk/asynk.sgml.gz

Format: postscript
Files: /usr/share/doc/asynk/asynk.ps.gz

Format: text
Files: /usr/share/doc/asynk/asynk.text.gz

Format: HTML
Index: /usr/share/doc/asynk/html/index.html
Files: /usr/share/doc/asynk/html/*.html
